# Generated by Django 5.1.2 on 2024-11-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0004_categoria_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
